### ISSUE TITLE
Missing localization strings

### ISSUE THREAD

**Issue by phenomen** [pafvel/dragonbane#1]
I was working on localization and found a few issues

1. **Missing localization:** Broken
![image](https://github.com/pafvel/dragonbane/assets/138311/1af452e4-c3b9-4edd-a2e0-117d85221c75)

2. **Missing title:** Weapon Features
![image](https://github.com/pafvel/dragonbane/assets/138311/e25fbc0b-279e-4802-816d-c07abd39947c)

3. **Missing title:** Bonus Armor
4. **Missing tooltips:** 
```
DoD.damageTypes.bludgeoningTooltip
DoD.damageTypes.piercingTooltip
DoD.damageTypes.slashingTooltip
```
![image](https://github.com/pafvel/dragonbane/assets/138311/41ffc5d7-80bf-4202-adf8-66bfd15c9fe8)

5. **Hardcoded ampersand:** Abilities & Spells
(it's Latin-only symbol and doesn't exist in other languages. Please add it to en.json so it will be possible to replace with "and")
![image](https://github.com/pafvel/dragonbane/assets/138311/8ce58889-f12d-47ca-8c90-f366ae4dce52)

**Comment by pafvel** [comment]
Thanks,

I have fixed  the issues in https://github.com/pafvel/dragonbane/commit/e4c2bc8063253b4f585fa101a92b460b42d06015.

They will be included in the next version of the system. No ETA right now, but hopefully within a week or so.

//Patrik P.

Från: Aleksandr ***@***.***>
Skickat: den 12 juli 2023 02:52
Till: ***@***.***>
Kopia: ***@***.***>
Ämne: [pafvel/dragonbane] Missing localization strings (Issue #1)


I was working on lozalization and found a few issues

  1.  Missing localization: Broken
[image]<https://user-images.githubusercontent.com/138311/252825543-1af452e4-c3b9-4edd-a2e0-117d85221c75.png>
  2.  Missing title: Weapon Features
[image]<https://user-images.githubusercontent.com/138311/252825620-e25fbc0b-279e-4802-816d-c07abd39947c.png>
  3.  Missing title: Bonus Armor
  4.  Missing tooltips:

DoD.damageTypes.bludgeoningTooltip

DoD.damageTypes.piercingTooltip

DoD.damageTypes.slashingTooltip

[image]<https://user-images.githubusercontent.com/138311/252825748-41ffc5d7-80bf-4202-adf8-66bfd15c9fe8.png>

  1.  Hardcoded ampersand: Abilities & Spells
(it's Latin-only symbol and doesn't exist in other languages. Please add it to en.json so it will be possible to replace with "and")
[image]<https://user-images.githubusercontent.com/138311/252825868-8ce58889-f12d-47ca-8c90-f366ae4dce52.png>
