### ISSUE TITLE
Torch item (better as a weapon)

### ISSUE THREAD

**Issue by MothMariner** [pafvel/dragonbane#12]
Are you in charge of the Core Rules add-on module? I'm struggling to find who to contact about it.

If you are: Torches are currently items rather than weapons, but weapons would make more sense.

Firstly they could take up a hand slot when held, as they should, and secondly they could then also have the correct stats included for when used as a weapon.

Sorry if I'm directing this suggestion to the wrong person, but if you know where I should be sending this that would be very helpful too. Thanks.

**Comment by pafvel** [comment]
I've had the same thought, but there are no stats for torches as weapons in the rules (the improvised weapon doesn't work like a weapon) and therefore I can't add it to the official module.

**Comment by MothMariner** [comment]
It says “small wooden club that does fire damage” on page 52, and _Wooden Club, Small_ is in the weapons list? And some enemies take damage differently for fire so I know they expect fire damage to happen somehow. But maybe I’m missing something.

**Comment by pafvel** [comment]
Ah! I had missed that. Thanks for the clarification. Will look into adding it.

**Comment by pafvel** [comment]
Will be in next update.
