### ISSUE TITLE
Swedish text in English version of Solo Adventure content

### ISSUE THREAD

**Issue by MothMariner** [pafvel/dragonbane#13]
In the journal Dragonbane - Solo Adventure: Alone in Deepfall Breach, page 2: Core Solo Tools, heading: Inspiration Table, the tables headers are all in Swedish:

<img width="648" alt="inspiration_table" src="https://github.com/pafvel/dragonbane/assets/81623344/a5d7df6a-4245-44ec-9bd3-7e8a0dca171a">

**Comment by pafvel** [comment]
Thanks! Fixed for next release.
