### ISSUE TITLE
Missing spaces between words in chat cards

### ISSUE THREAD

**Issue by struckyCZ** [pafvel/dragonbane#14]
Namely between words in skill roll chat cards, but possible elsewhere too - haven't checked everything. 
![image](https://github.com/pafvel/dragonbane/assets/80347865/df540073-354e-4825-a593-495a02f57d3f)

**Comment by pafvel** [comment]
Can't reproduce. Please disable all modules except the core dragonbane module. If the problem persists, please include browser version, foundry version and dragonbane system version.

**Comment by struckyCZ** [comment]
Aye, sorry. It wasn't my game, but friend's one. It was the Chat portraits module.
