### ISSUE TITLE
Can't modify skill level to lower than base chance

### ISSUE THREAD

**Issue by King-Wedgie** [pafvel/dragonbane#17]
**Foundry** v11.313
**Dragonbane** v1.4.0
_Modules disabled during testing_

To preface, I'm using the "Severe Injuries" optional rules, which is why skills would be getting edited down (some injuries permanently reduce skill levels). Setting a skill higher works as expected.

**To replicate**:
1) Launch Foundry and a Dragonbane world as normal
2) Create a new actor (can be player, NPC, or monster)
3) Edit any skill to lower than the base chance. The number should immediately revert back to base chance.
4) Edit the skill again. The new number should stick this time, however, if you make a roll, anything under the base chance still succeeds even if it's higher than the new number.
5) Attempting to edit a third time doesn't do anything; the text box doesn't even terminate when hitting the [Enter] key.
6) Editing *anything* else on the character sheet, closing the sheet, or refreshing the page will revert the number back to base.

**Comment by pafvel** [comment]
Thanks! Until this is addressed, you could do this as a workaround:

Change the skill type to Secondary, with the following side effects:
- It will move to the Secondary Skills section on the Skills tab.
- If it is your highest STR-based weapon skill, it will no longer be used to calculate your skill value for weapons with the Shield feature (can be addressed by removing the Shield feature and adding the weapon skill explicitly).

**Comment by pafvel** [comment]
Fixed by https://github.com/pafvel/dragonbane/commit/8ca507e08d47ceec2bae115c0e82da6b670de9f1
If skill value is 0 or empty, it will reset to base chance.
