### ISSUE TITLE
Unable to delete default Kin / Profession Heroic Abilities

### ISSUE THREAD

**Issue by Warhippo** [pafvel/dragonbane#18]
The rules allow for alternative Heroic abilities for Kin and Professions but I am unable to delete these from the character sheet.

**Comment by pafvel** [comment]
It can be done by creating new Kins/Professions with the abilities you want and then drop those onto the character.
Or you can remove the Kin/Profession and associated abilities by emptying the Kin/Profession field on the Background tab.

I will let this issue remain open as a reminder to make it more user friendly.

**Comment by Warhippo** [comment]
Magic! Thanks for letting me know :)

**Comment by pafvel** [comment]
For Professions you can also edit the character's profession directly, even drag and drop a new ability onto the progession, and the character will be updated automatically. This does not work for Kin, however. (This comment will remind me to fix that)

**Comment by Warhippo** [comment]
I think (for me) the easiest approach is to duplicate the Kin / Professions - give them an adjusted name, delete the Ability that goes with it, add in an appropriate one and then use that instead.
