### ISSUE TITLE
Cannot add heroic abilities to character sheet

### ISSUE THREAD

**Issue by nosirromx** [pafvel/dragonbane#19]
Not sure if I am doing something wrong, but I can't seem to add heroic abilities.  I can add kin abilities and profession abilities by clicking in the blank text area, but the text area for heroic abilities has no height and it seems impossible to click anywhere to add text.

![image](https://github.com/pafvel/dragonbane/assets/94464121/a748476e-b691-49bf-8603-e04dc505ca6d)

**Comment by pafvel** [comment]
Drag and drop Heroic Ability on to the character sheet.

**Comment by pafvel** [comment]
I might add a tooltip to explain, because it is not obvious.
