### ISSUE TITLE
Feature request - Damage numbers

### ISSUE THREAD

**Issue by mselberg** [pafvel/dragonbane#21]
Is it possible to add an toggle in the configuration to hide the calculation of damage rolls in the chat window to combat meta gaming.
Only printing the original damage number for the players and not the final damage that actually gets attributed to the monster/npc

Now you not only see a monsters armor but also if it's resistant or immune. Would be nice to be able to roleplay those numbers and make the users use skills like beastlore to find out whats happening.

**Comment by pafvel** [comment]
Players can only see the detailed damage information if they have at least Observer permission to the target, in which case they can also open the npc/monster sheet and see all details.
The damage number is only visible to players if they have at least the permission level in the "Permission to see Damage" setting.
There is no need for a feature toggle, unless I'm misunderstanding or if there's a bug I'm unaware of.

**Comment by mselberg** [comment]
Thanks! Iv'e been blind. Have been looking for the "Permission to see Damage" settings without finding it anywhere. It had the wrong setting. Works like a charm. Skit bakom spakarna helt enkelt!  Thanks for a super system!
