### ISSUE TITLE
Lift the limit of 18 on Basic Abilities / Grundegenskaper.

### ISSUE THREAD

**Issue by belsebubben** [pafvel/dragonbane#27]
It seems as if there is a hard limit on the Character Sheets of **18 on basic abilities** / Grundegenskaper. It would be fantastic if that could be lifted, not only would it no longer put a cap on fantasy, or houserules or the ability to use those sheets to create powerful and cool foes or npc. If for some reason one would want it could be colored somehow once it shot above 18 to highlight the fact that it is out of the ordinary, but out of the ordinary I would say is a good reason in the first place to play roleplaying games.

Thanks for the great work.

Kind regards
Carl

**Comment by pafvel** [comment]
The system tries to implement the official rules as closely as possible, and the cap is 18 in the rules. Although it would be technically possible to remove the cap, it is unclear what it would mean mechanically, for example when making a D20-roll against a value greater than 20. Thus, I have no intention to change the cap unless there are official rules for it.
