### ISSUE TITLE
Missing some options for IR sensor when using the Material Plane module

### ISSUE THREAD

**Issue by ReverendBlackPercy** [pafvel/dragonbane#28]
I'm using the module Material Plane together with an IR sensor to move tokens in Dragonbane, there is one problem though and that is that the options to calibrate the sensor isn't showing up in Dragonbane game.
It works in other games and I can calibrate in another game and then start Dragonbane after that and it stays calibrated but it would be nice to be able to do it in the game in case someone moves the tv or the sensor by accident.

![Skärmbild Dragonbane](https://github.com/pafvel/dragonbane/assets/155474010/637e20a3-5fef-4a37-8db6-34cc4e97a820)
![Skärmbild Pathfinder](https://github.com/pafvel/dragonbane/assets/155474010/3628f740-1220-456c-9c4b-3babe15db690)

**Comment by pafvel** [comment]
I can't open the config screen because I don't have the required hardware. Unable to fix this issue.

**Comment by ReverendBlackPercy** [comment]
Writing an update as of V13 this is now working as intended.
