### ISSUE TITLE
Feature Request: Add the ability to apply arbitrary damage and healing via the chat window.

### ISSUE THREAD

**Issue by arcos** [pafvel/dragonbane#3]
Right now the system is a bit inflexible as you are not able to apply damage or healing arbitrarily through the chat window. Sometimes it's necessary to do this (mistakes in setting up an attack roll, environmental damage, area of effect spells with multiple targets, etc.) `/damage` is a bit clunky as it needs to be in `[[]]` and then you have to click again after the die button renders in chat. `/damage` doesn't support combining dice types together (i.e. `/damage 1d6+1d4`). 

There doesn't appear to be a way to apply healing at all (correct me if I missed it), so users are left having to manually apply healing to tokens. The 5e system gets around this by making every die roll available for damage / healing in chat.

**Comment by pafvel** [comment]
Added capability to add damage and healing to selected token from normal die roill chat cards. See https://github.com/pafvel/dragonbane/commit/1def09d5ecb5885c771aa7944af7236b59828923.

**Comment by arcos** [comment]
Nice @pafvel !
