### ISSUE TITLE
French 

### ISSUE THREAD

**Issue by Harfang** [pafvel/dragonbane#31]
Hi, thank you very much for your work !
Please consider adding french translation for the system
[fr.json](https://github.com/pafvel/dragonbane/files/14118208/fr.json)

**Comment by Harfang** [comment]
[fr.json](https://github.com/pafvel/dragonbane/files/14125205/fr.json)
new version updated and corrected

**Comment by pafvel** [comment]
Resolved in https://github.com/pafvel/dragonbane/commit/efbd254d2b871872df7286d7f6e58b6a943849b2
