### ISSUE TITLE
Feature: Trained Skill Function

### ISSUE THREAD

**Issue by SerotoninRonin** [pafvel/dragonbane#33]
**Issue:** At characters generation currently there is no way to choose your Trained skills or indicate that they are trained.  Commonly, players are mistakenly clicking the "XP roll" checkbox thinking it is to indicate which skills you are Trained in.  The system already indicates which skills come with your Profession package.

**Suggested Feature**: add in a feature that allows the user to select a skill as Trained.  This would automatically calculate its unimproved score as base x2.

**Comment by pafvel** [comment]
Resolved by adding a dialog if user ckicks the mark checkbox before having advanced skills.
