### ISSUE TITLE
Enhancement: Sub Catagorize Rolls

### ISSUE THREAD

**Issue by jacobwojoski** [pafvel/dragonbane#39]
There's no way to tell if a roll was related to a weapon skill vs Core skill vs Secondary. (Attributes vs skills are fine from parsing the flavor text)

I know PF2e adds it as a **rolls.options.domains** field but other systems just describe it in the **rolls.flavor** text like DnD5e. 

I would like to use this to help categorize rolls for the Dice Stats module.

Add the skills related **Skill Type** to the flavor text or the roll object could be an great way to resolve the issue rather then all skills just saying *Skill*

Current Roll object with no way to see the type of skill: 
![image](https://github.com/pafvel/dragonbane/assets/124112219/3e7533d2-1286-4173-8030-71c60b33137a)

**Comment by pafvel** [comment]
I have considered adding info in msg.content to identify skill rolls, e.g. add "skill-roll" / "attribute-roll" and "data-skill-id" / "data-attribute", etc. Would that do the job?

**Comment by jacobwojoski** [comment]
Looks like it could do the job. I guess big thing is seeing the different types of skill rolls. Weapon skills vs secondary skills, vs primary skills. Dont quite know if the msg.content would get that granular or not. 

Currently there’s no way to tell the difference.

**Comment by jacobwojoski** [comment]
Doing a Bit more testing I can parse by checking the flavor string for Attack, Topple, Disarm, and Parry to partially solve the issue. 
Rolling a weapon skill from the Skills Tab will always just say "... Skill ..." with no way to tell what type of skill was rolled though.

**Comment by pafvel** [comment]
I would not recommend parsing localized text. Adding the skillId would let you find the skill and check skill type on the item in a language independent way.

**Comment by jacobwojoski** [comment]
True, Forgot entirely about text being localized. That would def could fix the skill issue. 

Although it would have issues telling if it was a damage roll or Attack roll at that point though as both of those wouldn't have any skill associated.

**Comment by jacobwojoski** [comment]
> I have considered adding info in msg.content to identify skill rolls, e.g. add classes "skill-roll" / "attribute-roll" and "data-skill-id" / "data-attribute", etc. Would that do the job?

Actually, then this could def work. I could just pull the skill ID from here and see the type, Otherwise see if its attack vs Attribute. Temp solution of text parsing and will update if this gets implemented.

**Comment by pafvel** [comment]
Resolved in https://github.com/pafvel/dragonbane/commit/06573f0963ea5b6268fc1845beb6d897e1b7e970
