### ISSUE TITLE
Feature Request: Add a boon if STR requirement is not reached

### ISSUE THREAD

**Issue by vt-tom** [pafvel/dragonbane#4]
If a character doesnt reach the STR requirement of a weapon, it would be cool if the system adds automatically a boon to the attack roll.

**Comment by arcos** [comment]
I think you mean a bane?

**Comment by vt-tom** [comment]
Yes sorry 🙃

**Comment by pafvel** [comment]
Resolved by https://github.com/pafvel/dragonbane/commit/d8193dcaf80261355962598f9b3ed0764408137c
