### ISSUE TITLE
Bug: Weird calculations in inventory

### ISSUE THREAD

**Issue by Azazel666** [pafvel/dragonbane#41]
At some numbers the calculations for weight in the inventory becomes weird.
Example: The item bandages is bought and contains 10 bandages in total and they have a weight of 1 for the item. that means 10x0.1 = 1. So we have setup the item as such.

On my character i one bought bandages and have since then used 3, so i'm left with 7 which should be shown as 0.7 in my pack. But this is for some reason showing 0.7000000000000001 instead. But this only happens on some quantity values, between 1-10 this happens on 3, 6 & 7 for me.
![2024-03-03 16_03_34-Foundry Virtual Tabletop - Opera](https://github.com/pafvel/dragonbane/assets/2535654/dc3da4c2-28a9-4914-a80b-b0cf9389d4d0)

On quantity 6 it also shows as 0.6000000000000001.
![2024-03-03 16_10_08-Foundry Virtual Tabletop - Opera](https://github.com/pafvel/dragonbane/assets/2535654/a03f0dfe-ce76-4964-a307-b770a6c14640)

But on 3 it shows 0.30000000000000004.
![2024-03-03 16_11_07-Foundry Virtual Tabletop - Opera](https://github.com/pafvel/dragonbane/assets/2535654/aa1cefc0-84bc-47e5-8f55-50074dba3c08)

**Comment by pafvel** [comment]
Fixed by https://github.com/pafvel/dragonbane/commit/cd8a1ae09ecf530bd5a052fdf1465fe8c21964c0
