### ISSUE TITLE
Feature Request: Scrolling status text

### ISSUE THREAD

**Issue by vt-tom** [pafvel/dragonbane#5]
The Foundry Core feature scrolling status text doesnt work. Its not shown on the tokens if i apply damage.

**Comment by pafvel** [comment]
Scrolling status text needs to be added by the system (it's not automatic, unfortunately).

Putting documentation link here for when it's time to implement: https://foundryvtt.com/api/classes/client.InterfaceCanvasGroup.html#createScrollingText

**Comment by vt-tom** [comment]
No problem, should i change my request title to: add scrolling status text?

**Comment by pafvel** [comment]
Resolved by https://github.com/pafvel/dragonbane/commit/5944abd6f8cf8f75ce8b1f89cbc7a284da0e002e
