### ISSUE TITLE
Dragonbane Core Rules module - broken link in RollTable, "Random Events - Outskirt"

### ISSUE THREAD

**Issue by Stew-rt** [pafvel/dragonbane#53]
I wasn't sure where to report this, as it's with the purchased module, "Dragonbane Core Rules"

Let me know if there's a better place.

There's a minor issue with the RollTable at:
`Dragonbane - Adventures/3. Outskirt/Random Events - Outskirt`

It has a broken link at result 3, Troll in the Barn.
It references an actor, `@UUID[Actor.9hXYTV2fbOckrKRy]{troll}`, which does not exist.
It should reference `@UUID[Actor.nQ3SHOJlCByiJ6Uq]{troll}`

**Comment by pafvel** [comment]
Thanks for the report! Link has been fixed and will be in the next update.
