### ISSUE TITLE
V12 Menu Issues

### ISSUE THREAD

**Issue by BytomMan** [pafvel/dragonbane#56]
Number of button issues with FVTT V12:

1) Certain menus, such as when editing scenes, SAVE won't exit the screen and it will stay locked on that menu.
2) Transition from daylight to night to daylight won't take effect unless exiting the application.

**Comment by pafvel** [comment]
Can't reproduce on Foundry v12.327, Dragonbane system version 1.8.3 and Chrome. It seems likely that you have a general Foundry issue, not a Dragonbane specific issue. Please check https://foundryvtt.com/article/requirements/ - especially the browser requirements. It maye also be an issue with one of your installed modules, try disabling them.
