### ISSUE TITLE
Feature Request: Used Action indicator in Combat

### ISSUE THREAD

**Issue by vt-tom** [pafvel/dragonbane#6]
It would be nice having a used Action indicator in the combat. Because its not easy handling bigger fights with much combatants and used actions which could not be used for the reaction.

This doesnt have to be automatically. But a check or something like this on the char sheet would be nice.

If automation is possible:
- A check in the roll dialog: use action
- If used, check the action used on the sheet
- after a round, reset all used actions from the actors which are in combat

**Comment by pafvel** [comment]
Not planning to build this into the system. The YZE Combat module can be used to mark used actions.
