### ISSUE TITLE
YZE Combat interop

### ISSUE THREAD

**Issue by aMediocreDad** [pafvel/dragonbane#7]
Dragonbane-style initiative now works with YZE Combat's latest version (1.1.0). 

However, a few features are still missing and are best left to be implemented in the system with required API changes in YZE Combat resolved upstream.

- Drawing initiative each round should take into account heroic ability: https://github.com/fvtt-fria-ligan/yearzero-combat-fvtt/issues/27
- Surprise round and drawing specific initiatives (could be handled by YZE Combat).

CC @tak5haka

**Comment by Stefouch** [comment]
> Surprise round and drawing specific initiatives

The GM can right-click a combattant, select Update, and choose an initiative card before starting the combat.

BUT, with the reset of initiative at each the start of each round in Dragonbane, that could possibly not work anymore.

**Comment by pafvel** [comment]
Due to abilities being Items, any associated automation should also take place in the Item unless it's something very generic. The "Lock Initiative" solution makes it possible to automate the Veteran ability in the future using eg. active effects or "on activation" scripts on abilities.

**Comment by aMediocreDad** [comment]
I consider this issue fixed. Fixing initiative at start of combat works as intended, and now locking initiative works as intended.
