### ISSUE TITLE
Formula cant be evaluated error repeatedly

### ISSUE THREAD

**Issue by mouvitz** [pafvel/dragonbane#70]
From the moment I create a custom weapon and add it to a character sheet I begin to get an error saying _Formula can not be evaluated_ whenever I do anything.

![bild](https://github.com/user-attachments/assets/b26c3ced-719f-4fac-b801-32499bae8513)

![bild](https://github.com/user-attachments/assets/fab791db-308a-4370-a4b1-0ba61c74ec64)

![bild](https://github.com/user-attachments/assets/001a9b48-8612-4d2a-94ad-6922cf2535e8)

![bild](https://github.com/user-attachments/assets/e1927271-95a1-475c-a52f-4bb25ea7dc67)

The item that I made:
![bild](https://github.com/user-attachments/assets/a18b58e3-ab39-411f-a620-92104c6756ba)

**Comment by mouvitz** [comment]
Changing the _Räckvidd_ parameter on the item to a number fixed this.

**Comment by pafvel** [comment]
The correct formula for Range/Räckvidd uses @str for Strength, etc. Numbers work too, which you already figured out.
