### ISSUE TITLE
Add possibility to modify dice rolls with +- value.

### ISSUE THREAD

**Issue by belsebubben** [pafvel/dragonbane#83]
As a gamemaster I may want to adjust dice rolls up or by a certain number instead of only adding boons and banes to rolls, a simple extra field "+/-" with the same kind of selection as the banes / boons would be awesome. It can be done manually of course however it would be really nice to have the feature in there as it allows for more streamlined gameplay.

Thanks for the nice job with the module.

Kind regards.
Carl

**Comment by pafvel** [comment]
I understand why it would be useful, but it is not covered by the official rules so I will not add it to the official system at this time. Fingers crossed, modifiers will be added in a future rules expansion.
